version: "3"
services:
  user-profile:
    build: 
        context: .
        args: 
          NODE_ENV: prod
    environment:
      - NODE_ENV=prod
      - MONGODB_URI=mongodb://swiftycareer_dev:swiftycareer@23.242.50.55:27017/?authSource=admin
      - JWT_SECRET=1304b28485f34eacb1bed092f62d84e6
      - JWT_REFRESH_EXP=600
    command: node src/server/index.js