version: "3"
services:
  user-profile:
    build: 
      context: .
      args: 
        NODE_ENV: dev
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./src/server/.env.dev